dist: trusty
addons:
  chrome: stable
language: node_js
before_install:
- export TZ=Europe/Zurich
- export CHROME_BIN=google-chrome-stable
- gem install mdl
- npm install -g @angular/cli
# greenkeeper-lockfile
cache:
  directories:
  - node_modules
# before_script: greenkeeper-lockfile-update
script: npm run ci
# after_script: greenkeeper-lockfile-upload
env:
  global:
    secure: "nPbST7sAYWuqbqmk0eECUv595EHUJTPRygrKt57pAwlXYidZsyYTgW1phcrXY2ByVVNsCkVusMK0O/iIgVMk1xSKERFjlW5ghA3oD++lxEeNxR/JTwIrRJID3RIyo7DTPVu0mEbB9AmWyJMUJU1ZL4P7qeXOIlzzzfJ+p3Jw/YkKffjGaA9c97/onBU0tmr0RZPeQy2rC6NQYDnpjjuSTj54eIHzpoXyl1ngTuY15pdyPPQPD/Jab6nqbhv/nr2zQtONOEbA+BODc0CfCxRTeOdpZ+n9j5WzgqELiP5u7R9y5ZW1An47kHCXGQqTmrSr2zR7Gg0boebjfZwwtfGkJDFeJR9U2oxsUPMFZjkNzQaZyOHQc36vSbhedeLyc/WgkI6skD9x9qb3b53Jh1pAryLpCIDwoo+CW51E7U5Ak4JzgYBUFqSAe57fw6nexazEvcWeR8jwBUFBXjt5WYBG/Gi4RdCB7IvYzzLP7WL1btf0mNDgrRdu9erqpn6p3h66XIFqJU06CiUYIDZOTu73euj4vmPs93AwtZhuCaKI8diEldKt9Fg7pgKTHeKAZZyfJqkwd6tp2FizsnplTP7PoIqEaiBWTVD9INc3PanvHhqJYSl47lVjiexMcZPLD2ZeLSrkeYqMI8v6mY3+NOW2SLaG3Fa+w6C0idKfhBSdan8="
#   - secure: TODO
# after_success:
# - npm install -g codeclimate-test-reporter
# - CODECLIMATE_REPO_TOKEN=TODO codeclimate-test-reporter < coverage/lcov.info
# - CODECLIMATE_API_HOST=https://codebeat.co/webhooks/code_coverage CODECLIMATE_REPO_TOKEN=TODO codeclimate-test-reporter < coverage/lcov.info
# - npm install -g codacy-coverage
# - cat coverage/lcov.info | codacy-coverage
# - npm install -g codecov
# - codecov
before_deploy:
- npm run build-prod
# - npm i -g webpack && cd functions && npm i && webpack && cd ..
deploy:
  - provider: firebase
    skip_cleanup: true
    on:
      branch: master
    token:
      secure: Bvc0QWz/HY54Z+axfhryD0XNXNozhEHk92XocGOfyNP+4jJ/VU6+uNMF/u+mLmg71OagPbXIc3o7Ty2a49nvmBkZRl/fp5tdJsKMecFFwcIkqg277GEgZWc+FD8Efeo/iDPT3hjV6ntxLpERteglNe9f5Mpc206UmnXCUx0KofnqGhcs4xbCbJwi8qiwHcDD9BUi2ozoVu2h9asQ1IAkx5W/RaUkzUO9YaS+GxYnZuxhAr1W2e5hFtyE+MiYp4REr7BKEn3/MBYh5ud4Ae9y1Rk+RSAL8KcSIf2IFQbcmwrggNngEXzFy29OXPWL+xGjzW1yBqCNWSRVgfk4bRgvX3JwNfldd9S5t7KMVca9OnRVoGaOF+ACBGgDqxz9VQyG6/IQMNpVKxxAiJVmAwIh9G2oX+8esw9q4OpQ1N7lFtE9sPhCCh3M5n3WPq0+NuA68669xC1KkIEBbU5od5C7adyNYLmxo/38WtEuQCYuGAJ3OrE6RfBF0js5dLWyfNJq9CT5HrW2m5vQYsjZnrrjG8l9FhlWtqNs5ssN47lQbaV4UH6k1qu6GxJ2aJ5R/5J43bm5sIXUj4MNvszte2/keDQ4oEOlhW6iyGFQnza4P0wo3Za+52q1IAJYSIgn0TeA7kF8S6oym53j3xwBOQ+RIMJR8Mnvii0w2KlnhrNbnDg=
    project: gdg-website-master
  - provider: firebase
    skip_cleanup: true
    on:
      branch: develop
    token:
      secure: Bvc0QWz/HY54Z+axfhryD0XNXNozhEHk92XocGOfyNP+4jJ/VU6+uNMF/u+mLmg71OagPbXIc3o7Ty2a49nvmBkZRl/fp5tdJsKMecFFwcIkqg277GEgZWc+FD8Efeo/iDPT3hjV6ntxLpERteglNe9f5Mpc206UmnXCUx0KofnqGhcs4xbCbJwi8qiwHcDD9BUi2ozoVu2h9asQ1IAkx5W/RaUkzUO9YaS+GxYnZuxhAr1W2e5hFtyE+MiYp4REr7BKEn3/MBYh5ud4Ae9y1Rk+RSAL8KcSIf2IFQbcmwrggNngEXzFy29OXPWL+xGjzW1yBqCNWSRVgfk4bRgvX3JwNfldd9S5t7KMVca9OnRVoGaOF+ACBGgDqxz9VQyG6/IQMNpVKxxAiJVmAwIh9G2oX+8esw9q4OpQ1N7lFtE9sPhCCh3M5n3WPq0+NuA68669xC1KkIEBbU5od5C7adyNYLmxo/38WtEuQCYuGAJ3OrE6RfBF0js5dLWyfNJq9CT5HrW2m5vQYsjZnrrjG8l9FhlWtqNs5ssN47lQbaV4UH6k1qu6GxJ2aJ5R/5J43bm5sIXUj4MNvszte2/keDQ4oEOlhW6iyGFQnza4P0wo3Za+52q1IAJYSIgn0TeA7kF8S6oym53j3xwBOQ+RIMJR8Mnvii0w2KlnhrNbnDg=
    project: gdg-website-develop
